databases:
  - name: frogazz-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: pronostics-api-server
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://pronostics-api-server.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: frogazz-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: frogazz-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: frogazz-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: frogazz-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: frogazz-db
          property: password
      - key: PAYDUNYA_MODE
        value: live
      - key: PAYDUNYA_IPN_URL
        value: https://pronostics-api-server.onrender.com/api/v1/paydunya/ipn
      - key: PAYDUNYA_RETURN_URL
        value: https://pronostics-api-server.onrender.com/api/v1/paydunya/return
      - key: PAYDUNYA_CANCEL_URL
        value: https://pronostics-api-server.onrender.com/api/v1/paydunya/cancel
      - key: PAYDUNYA_CURRENCY
        value: XOF
